#!/usr/bin/env python
import sys,subprocess

if len(sys.argv) > 1:
  if sys.argv[1] == '--help' or sys.argv[1] == '-h':
    print('Usage: Script to automate the use of a commnand across all available terminals')
    print('Usage: all-terms COMMAND')
    print('Usage: COMMAND is what will be run on all available terminals')
  else:
    command = []
    for value in range(1,len(sys.argv)):
      command.append(sys.argv[value])
    full_command = []
    for value in range(1,25):
      full_command = ['sudo','ttyecho','-n','/dev/tty'+str(value)]
      for string in command:
        full_command.append(string)
      p = subprocess.Popen(full_command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
      output,error = p.communicate()
else:
  print("no command given")
